version: '3.9'

services:
  web:
    build: .
    command: >
      bash -c "python3 /app/manage.py makemigrations main --noinput  &&
             python3 /app/manage.py migrate && printf 'yes' &&
             python3 /app/manage.py runserver 0.0.0.0:2000"
    #             gunicorn core.wsgi:application --forwarded-allow-ips='*' --workers=4 --log-level info --bind 0.0.0.0:8002"
    volumes:
      - .:/app
    ports:
      - 2000:2000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  db_data:
